<?php
/**
 * Dynamic render callback for the videomuxr/video block.
 *
 * @param array  $attributes Block attributes.
 * @param string $content    Inner blocks content (unused).
 *
 * @package VideoMuxr
 */

defined( 'ABSPATH' ) || exit;

$playback_id = isset( $attributes['playbackId'] )
	? sanitize_text_field( $attributes['playbackId'] )
	: '';

if ( '' === $playback_id ) {
	return;
}

wp_enqueue_script(
	'mux-player',
	'https://cdn.jsdelivr.net/npm/@mux/mux-player@3',
	array(),
	VIDEOMUXR_VERSION,
	array( 'in_footer' => true )
);
add_filter( 'script_loader_tag', 'videomuxr_add_module_type', 10, 2 );
?>
<figure <?php echo get_block_wrapper_attributes(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- safe, generated by WordPress core. ?>>
	<mux-player
		playback-id="<?php echo esc_attr( $playback_id ); ?>"
		controls
		playsinline
	></mux-player>
</figure>
