<?php
/**
 * Dynamic render callback for the videomuxr/video block.
 *
 * @param array  $attributes Block attributes.
 * @param string $content    Inner blocks content (unused).
 *
 * @package VideoMuxr
 */

defined( 'ABSPATH' ) || exit;

$playback_id = isset( $attributes['playbackId'] )
	? sanitize_text_field( $attributes['playbackId'] )
	: '';

if ( '' === $playback_id ) {
	return;
}

// Convert Mux "16:9" format to CSS "16/9" for the aspect-ratio property.
$aspect_ratio     = sanitize_text_field( $attributes['aspectRatio'] ?? '' );
$css_aspect_ratio = '' !== $aspect_ratio ? str_replace( ':', '/', $aspect_ratio ) : '';
$player_style     = $css_aspect_ratio
	? 'aspect-ratio:' . $css_aspect_ratio . ';display:block;width:100%;'
	: 'display:block;width:100%;';

wp_enqueue_script(
	'mux-player',
	'https://cdn.jsdelivr.net/npm/@mux/mux-player@3',
	array(),
	VIDEOMUXR_VERSION,
	array( 'in_footer' => true )
);
add_filter( 'script_loader_tag', 'videomuxr_add_module_type', 10, 2 );
?>
<figure <?php echo get_block_wrapper_attributes(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- safe, generated by WordPress core. ?>>
	<mux-player
		playback-id="<?php echo esc_attr( $playback_id ); ?>"
		controls
		playsinline
		style="<?php echo esc_attr( $player_style ); ?>"
	></mux-player>
</figure>
